#!/bin/sh
#
# Try to unmount all udiskie mounts before suspend

[ -n "${PM_FUNCTIONS}" ] && . "${PM_FUNCTIONS}"

case "$1" in
	hibernate|suspend)
		[ -x "$(which udiskie-umount)" -a -n "$(which udiskie-umount)" ] && \
			$(which udiskie-umount) --all --lock --detach
		;;
	*)
		exit $NA
		;;
esac
 
exit 0
